### ISSUE TITLE
Error: EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by dodieboy** [hemisemidemipresent/NKsku#1]
Hey, i tried to unpack a DGDATA file (Profile.save) using the upacking code but it gets the following error below. I tried using `nksku.dgdata.decode(bytes).toString('utf-8');` and the it work great with no decryption error. Any idea what I did wrong?

```
PS C:\Users\Alan\Desktop\SAS4\a> node --trace-warnings index.js 
Promise { <pending> }
(node:16788) UnhandledPromiseRejectionWarning: Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at Object.unpack (C:\Users\Alan\Desktop\SAS4\a\node_modules\nksku\nksave.js:46:30)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:16788) Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at Object.unpack (C:\Users\Alan\Desktop\SAS4\a\node_modules\nksku\nksave.js:46:30)
(node:16788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by hemisemidemipresent** [comment]
Profile.save is not encoded in DGDATA, at least not Btd6's Profile.save

**Comment by dodieboy** [comment]
O, i see. Yup this is a SAS profile.save file
